[project]
name = "fastapi-base"
version = "0.1.0"
description = "API base structure to create api's with fastAPI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard-no-fastapi-cloud-cli]>=0.118.0",
    "pydantic-settings>=2.11.0",
]
